[versions]

gson = "2.13.1"
jsonPath = "2.9.0"
jsoup = "1.16.2"
jsoupxpath = "2.5.3"
rhino = "1.8.0"
coroutines = "1.10.2"

#不要更新版本
hutool = "5.8.22"

[libraries]

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonPath" }
# issue #3811，不要更新版本，新版引入了一个破坏性变更（详见https://github.com/jhy/jsoup/pull/2017）
# 若要升级请确保相关代码不会受此变更影响（如AnalyzeByJSoup.kt、JsoupXpath库等）
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsoupxpath = { module = "cn.wanghaomiao:JsoupXpath", version.ref = "jsoupxpath" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

hutool-crypto = { module = "cn.hutool:hutool-crypto", version.ref = "hutool" }
mozilla-rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
